# Exported from Render on 2025-12-01T11:31:53Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: catalogo-limacalixto-api
      runtime: node
      repo: https://github.com/danieldavid-souza/catalogo-online-limacalixtoV4
      plan: free
      region: oregon
      buildCommand: npm install
      startCommand: node server.js
      autoDeployTrigger: commit
      rootDir: backend
